name: Ma premiere action

on: [push, pull_request]

jobs:
  job_un:
    runs-on: ubuntu-latest
    steps:
      - name: afficher les fichiers (avant checkout)
        run: ls -R
      - name: Recupere le code (checkout)
        uses: actions/checkout@v4
      - name: afficher les fichiers (apres checkout)
        run: ls -R
      - name: Installer PHP et PHPCS
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpcs
      - name: Lancer le lint (phpcs)
        run: phpcs --standard=PSR12 TP5/src/ 
